### PR TITLE
keys() on EL5/6 needs a hash, not only a hashref 

### LINKED ISSUE #39: 15.2.0-rc4: ncm-ncd broken on SL6
Showstopper for 15.2...

After upgrade to 15.2.0, any attempt to run `ncm-ncd` on a SL6 machine results in the following error:

```
[root@grid63 ~]# ncm-ncd --configure spma
Type of arg 1 to keys must be hash (not map iterator) at /usr/sbin/ncm-ncd line 501, near "@ARGV)"
Execution of /usr/sbin/ncm-ncd aborted due to compilation errors.
```

Any idea?

### PR DESCRIPTION
**Pull request by stdweird**
(and certainly not a hash iterator)
fixes #39

### CODE REVIEW

**Comment by stdweird** [comment]
Tested on EL5/6/7 with
```
perl -e 'print join("\n", sort(keys( %{ {map {$_ => 1} @ARGV} } )) )' c b a
```

**Comment by stdweird** [comment]
@jouvin my apologies (you can recover with `yum downgrade ncm-ncd-14.10.0 -y`)

**Comment by jrha** [comment]
Fixes issue on SL6 at RAL.

**Comment by jouvin** [comment]
@stdweird no problem, this is the role of a beta tester! Merging.
