### ISSUE TITLE
15.2.0-rc4: ncm-ncd broken on SL6

### ISSUE THREAD

**Issue by jouvin** [quattor/ncm-ncd#39]
Showstopper for 15.2...

After upgrade to 15.2.0, any attempt to run `ncm-ncd` on a SL6 machine results in the following error:

```
[root@grid63 ~]# ncm-ncd --configure spma
Type of arg 1 to keys must be hash (not map iterator) at /usr/sbin/ncm-ncd line 501, near "@ARGV)"
Execution of /usr/sbin/ncm-ncd aborted due to compilation errors.
```

Any idea?

**Comment by jouvin** [comment]
Added to 15.2.0-rc4 status (https://github.com/quattor/release/issues/80).

**Comment by jrha** [comment]
@stdweird this is your code, can you illuminate?

**Comment by jrha** [comment]
Awesome.

**Comment by jrha** [comment]
Duplicated at RAL on SL6, #40 does indeed fix it.

**Comment by jouvin** [comment]
I'm waiting for the new RC to test. I have no doubt it will fix the pb!
